// <auto-generated />
using System;
using GestionBibliotheque.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionBibliotheque.Migrations
{
    [DbContext(typeof(BibliothequeDbContext))]
    [Migration("20260529141218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionBibliotheque.Models.Abonnement", b =>
                {
                    b.Property<int>("IdAbonnment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_ABONNMENT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAbonnment"));

                    b.Property<string>("CodeReference")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CODE_REFERENCE");

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("DATE_DEBUT");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("DATE_FIN");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("datetime")
                        .HasColumnName("DATE_PAIEMENT");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_MEMBRE");

                    b.Property<int?>("IdType")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_TYPE");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MODE_PAIEMENT");

                    b.Property<float?>("Montant")
                        .HasColumnType("float")
                        .HasColumnName("MONTANT");

                    b.Property<string>("ReferencePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("REFERENCE_PAIEMENT");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUT")
                        .HasDefaultValueSql("'inactif'");

                    b.Property<string>("StatutPaiement")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUT_PAIEMENT")
                        .HasDefaultValueSql("'en_attente'");

                    b.HasKey("IdAbonnment")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdType" }, "FK_CONTENIR");

                    b.HasIndex(new[] { "IdMembre" }, "FK_SOUSCRIRE");

                    b.HasIndex(new[] { "CodeReference" }, "UK_CODE_REFERENCE")
                        .IsUnique();

                    b.ToTable("abonnement", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Alerte", b =>
                {
                    b.Property<int>("IdAlerte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_ALERTE_");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAlerte"));

                    b.Property<DateOnly?>("DateDemande")
                        .HasColumnType("date")
                        .HasColumnName("DATE_DEMANDE");

                    b.Property<DateOnly?>("DateNotification")
                        .HasColumnType("date")
                        .HasColumnName("DATE_NOTIFICATION");

                    b.Property<bool?>("EstTraitee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EST_TRAITEE")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("IdLivre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_LIVRE");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_MEMBRE");

                    b.Property<int?>("IdNotification")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_NOTIFICATION");

                    b.Property<string>("MoyenNotification")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MOYEN_NOTIFICATION");

                    b.HasKey("IdAlerte")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdNotification" }, "FK_ALERTE_NOTIF");

                    b.HasIndex(new[] { "IdMembre" }, "FK_DEMANDER");

                    b.HasIndex(new[] { "IdLivre" }, "FK_RECEVOIR");

                    b.ToTable("alerte", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_CATEGORIE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategorie"));

                    b.Property<string>("Libelle")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LIBELLE");

                    b.HasKey("IdCategorie")
                        .HasName("PRIMARY");

                    b.ToTable("categorie", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.DetailEmprunt", b =>
                {
                    b.Property<int>("IdEmprunt")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_EMPRUNT");

                    b.Property<int>("IdLivre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_LIVRE");

                    b.Property<DateOnly?>("DateRetourPrevu")
                        .HasColumnType("date")
                        .HasColumnName("DATE_RETOUR_PREVU");

                    b.Property<DateOnly?>("DateRetourReel")
                        .HasColumnType("date")
                        .HasColumnName("DATE_RETOUR_REEL");

                    b.Property<decimal?>("MontantPenalite")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MONTANT_PENALITE");

                    b.Property<int?>("NbJourRetard")
                        .HasColumnType("int(11)")
                        .HasColumnName("NB_JOUR_RETARD");

                    b.HasKey("IdEmprunt", "IdLivre")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdLivre" }, "FK_CIF1");

                    b.ToTable("detail_emprunt", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Emprunt", b =>
                {
                    b.Property<int>("IdEmprunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_EMPRUNT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEmprunt"));

                    b.Property<DateOnly?>("DateEmprunt")
                        .HasColumnType("date")
                        .HasColumnName("DATE_EMPRUNT");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_MEMBRE");

                    b.Property<int>("IdUserEmprunt")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_USER_EMPRUNT");

                    b.Property<int?>("IdUserRetour")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_USER_RETOUR");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('en_cours','retourne','en_retard')")
                        .HasColumnName("STATUT")
                        .HasDefaultValueSql("'en_cours'");

                    b.HasKey("IdEmprunt")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdMembre" }, "FK_EFFECTUER");

                    b.HasIndex(new[] { "IdUserEmprunt" }, "FK_ENREGISTRER");

                    b.HasIndex(new[] { "IdUserRetour" }, "FK_VALIDER");

                    b.ToTable("emprunt", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Livre", b =>
                {
                    b.Property<int>("IdLivre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_LIVRE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLivre"));

                    b.Property<DateOnly?>("AnneePublication")
                        .HasColumnType("date")
                        .HasColumnName("ANNEE_PUBLICATION");

                    b.Property<string>("Auteur")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("AUTEUR");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Editeur")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EDITEUR");

                    b.Property<string>("Emplacement")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EMPLACEMENT");

                    b.Property<int?>("IdCategorie")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_CATEGORIE");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LANGUE");

                    b.Property<decimal?>("QuantiteDisponible")
                        .HasPrecision(20)
                        .HasColumnType("decimal(20)")
                        .HasColumnName("QUANTITE_DISPONIBLE");

                    b.Property<decimal?>("QuantiteTotal")
                        .HasPrecision(20)
                        .HasColumnType("decimal(20)")
                        .HasColumnName("QUANTITE_TOTAL");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUT");

                    b.Property<string>("Titre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TITRE");

                    b.HasKey("IdLivre")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCategorie" }, "ID_CATEGORIE");

                    b.ToTable("livre", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Membre", b =>
                {
                    b.Property<int>("IdMembre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_MEMBRE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMembre"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ADRESSE");

                    b.Property<DateOnly?>("DateInscription")
                        .HasColumnType("date")
                        .HasColumnName("DATE_INSCRIPTION");

                    b.Property<string>("Mail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MAIL");

                    b.Property<string>("Nom")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NOM");

                    b.Property<string>("Prenom")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PRENOM");

                    b.Property<string>("Sexe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SEXE");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext")
                        .HasColumnName("STATUT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("TELEPHONE");

                    b.HasKey("IdMembre")
                        .HasName("PRIMARY");

                    b.ToTable("membre", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_NOTIFICATION");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("DATE_CREATION")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<DateTime?>("DateLue")
                        .HasColumnType("datetime")
                        .HasColumnName("DATE_LUE");

                    b.Property<bool?>("EstLue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EST_LUE")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("IdMembre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_MEMBRE");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("ID_UTILISATEUR");

                    b.Property<string>("Lien")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LIEN");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TITRE");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("TYPE");

                    b.HasKey("IdNotification")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdMembre" }, "FK_NOTIF_MEMBRE");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_RESERVATION");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReservation"));

                    b.Property<DateOnly?>("DateReservation")
                        .HasColumnType("date")
                        .HasColumnName("DATE_RESERVATION");

                    b.Property<int?>("IdLivre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_LIVRE");

                    b.Property<int>("IdMembre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_MEMBRE");

                    b.Property<string>("Statut")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STATUT");

                    b.HasKey("IdReservation")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdLivre" }, "FK_CIF");

                    b.HasIndex(new[] { "IdMembre" }, "FK_FAIRE");

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.TypeAbonnement", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_TYPE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdType"));

                    b.Property<string>("Libelle")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LIBELLE");

                    b.Property<float?>("Tarif")
                        .HasColumnType("float")
                        .HasColumnName("TARIF");

                    b.HasKey("IdType")
                        .HasName("PRIMARY");

                    b.ToTable("type_abonnement", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_UTILISATEUR");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<int?>("IdMembre")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_MEMBRE");

                    b.Property<string>("Login")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ROLE");

                    b.HasKey("IdUtilisateur")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdMembre" }, "FK_USER_MEMBRE");

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Abonnement", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Membre", "IdMembreNavigation")
                        .WithMany("Abonnements")
                        .HasForeignKey("IdMembre")
                        .IsRequired()
                        .HasConstraintName("FK_SOUSCRIRE");

                    b.HasOne("GestionBibliotheque.Models.TypeAbonnement", "IdTypeNavigation")
                        .WithMany("Abonnements")
                        .HasForeignKey("IdType")
                        .HasConstraintName("FK_CONTENIR");

                    b.Navigation("IdMembreNavigation");

                    b.Navigation("IdTypeNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Alerte", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Livre", "IdLivreNavigation")
                        .WithMany("Alertes")
                        .HasForeignKey("IdLivre")
                        .IsRequired()
                        .HasConstraintName("FK_RECEVOIR");

                    b.HasOne("GestionBibliotheque.Models.Membre", "IdMembreNavigation")
                        .WithMany("Alertes")
                        .HasForeignKey("IdMembre")
                        .IsRequired()
                        .HasConstraintName("FK_DEMANDER");

                    b.HasOne("GestionBibliotheque.Models.Notification", "IdNotificationNavigation")
                        .WithMany("Alertes")
                        .HasForeignKey("IdNotification")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ALERTE_NOTIF");

                    b.Navigation("IdLivreNavigation");

                    b.Navigation("IdMembreNavigation");

                    b.Navigation("IdNotificationNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.DetailEmprunt", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Emprunt", "IdEmpruntNavigation")
                        .WithMany("DetailEmprunts")
                        .HasForeignKey("IdEmprunt")
                        .IsRequired()
                        .HasConstraintName("FK_CIF2");

                    b.HasOne("GestionBibliotheque.Models.Livre", "IdLivreNavigation")
                        .WithMany("DetailEmprunts")
                        .HasForeignKey("IdLivre")
                        .IsRequired()
                        .HasConstraintName("FK_CIF1");

                    b.Navigation("IdEmpruntNavigation");

                    b.Navigation("IdLivreNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Emprunt", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Membre", "IdMembreNavigation")
                        .WithMany("Emprunts")
                        .HasForeignKey("IdMembre")
                        .IsRequired()
                        .HasConstraintName("FK_EFFECTUER");

                    b.HasOne("GestionBibliotheque.Models.Utilisateur", "IdUserEmpruntNavigation")
                        .WithMany("EmpruntIdUserEmpruntNavigations")
                        .HasForeignKey("IdUserEmprunt")
                        .IsRequired()
                        .HasConstraintName("FK_ENREGISTRER");

                    b.HasOne("GestionBibliotheque.Models.Utilisateur", "IdUserRetourNavigation")
                        .WithMany("EmpruntIdUserRetourNavigations")
                        .HasForeignKey("IdUserRetour")
                        .HasConstraintName("FK_VALIDER");

                    b.Navigation("IdMembreNavigation");

                    b.Navigation("IdUserEmpruntNavigation");

                    b.Navigation("IdUserRetourNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Livre", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Categorie", "IdCategorieNavigation")
                        .WithMany("Livres")
                        .HasForeignKey("IdCategorie")
                        .HasConstraintName("livre_ibfk_1");

                    b.Navigation("IdCategorieNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Notification", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Membre", "IdMembreNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdMembre")
                        .HasConstraintName("FK_NOTIF_MEMBRE");

                    b.Navigation("IdMembreNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Reservation", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Livre", "IdLivreNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("IdLivre")
                        .HasConstraintName("FK_CIF");

                    b.HasOne("GestionBibliotheque.Models.Membre", "IdMembreNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("IdMembre")
                        .IsRequired()
                        .HasConstraintName("FK_FAIRE");

                    b.Navigation("IdLivreNavigation");

                    b.Navigation("IdMembreNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Utilisateur", b =>
                {
                    b.HasOne("GestionBibliotheque.Models.Membre", "IdMembreNavigation")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdMembre")
                        .HasConstraintName("FK_USER_MEMBRE");

                    b.Navigation("IdMembreNavigation");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Categorie", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Emprunt", b =>
                {
                    b.Navigation("DetailEmprunts");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Livre", b =>
                {
                    b.Navigation("Alertes");

                    b.Navigation("DetailEmprunts");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Membre", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("Alertes");

                    b.Navigation("Emprunts");

                    b.Navigation("Notifications");

                    b.Navigation("Reservations");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Notification", b =>
                {
                    b.Navigation("Alertes");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.TypeAbonnement", b =>
                {
                    b.Navigation("Abonnements");
                });

            modelBuilder.Entity("GestionBibliotheque.Models.Utilisateur", b =>
                {
                    b.Navigation("EmpruntIdUserEmpruntNavigations");

                    b.Navigation("EmpruntIdUserRetourNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
